services:
  server:
    image: itzg/minecraft-server:java21-alpine
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: "PAPER"
      MEMORY: "2048M"
      VERSION: "1.21.8"
      MOTD: "Deablr Survival Test"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      FORCE_GAMEMODE: "true"
      ENABLE_COMMAND_BLOCK: "true"
      OPS: |-
        Ryxian
      ENABLE_WHITELIST: "true"
      WHITELIST: |-
        Ryxian
    volumes:
      - "./mc-worlds/world:/data/world"
      - "./mc-worlds/world_nether:/data/world_nether"
      - "./mc-worlds/world_the_end:/data/world_the_end"
